sudo: required

services:
- docker

before_install:
- docker build -t build_ubuntu_20.3 docker/ubuntu_20.3/
- docker build -t build_centos_20.3 docker/centos_20.3/


script:
- docker run -v $TRAVIS_BUILD_DIR:/home/sd/ build_ubuntu_20.3 /bin/sh -c "cd /home/sd/; make all; make test"
- docker run -v $TRAVIS_BUILD_DIR:/home/sd/ build_centos_20.3 /bin/sh -c "cd /home/sd/; make all; make test"

