sudo: required

language: erlang

otp_release:
- 18.0
- 18.1
- 18.2
- 18.2.1
- 18.3
- 19.0
- 19.1

services:
- docker

before_install:
- kerl list installations
- docker build -t build_ubuntu https://raw.githubusercontent.com/systemd/erlang-sd_notify/master/docker/ubuntu_18_3/Dockerfile
- docker images

script:
- docker run -v $TRAVIS_BUILD_DIR:/home/sd/ build_ubuntu /bin/sh -c "cd /home/sd/; make all; make test"
